### ISSUE TITLE
Decimal precision and scale

### ISSUE THREAD

**Issue by sod1102** [zzzprojects/EntityFrameworkExtras#19]
Is there a way to set the precision and scale for a StoredProcedureParameter attribute?

**Comment by stamminator** [comment]
@JonathanMagnan Any chance this might get looked at now that the project has recently been revisited?

**Comment by JonathanMagnan** [comment]
Hello @stamminator ,

Definitively a good chance!

One of my employees is working on this project every Friday, he already flagged this issue as a "TODO" and since you have shown some interest, I believe he will probably do it in priority this Friday or the next one.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by stamminator** [comment]
Glad to hear! Excited to see this great library get some QOL love. You guys rock.

###### Hire me

**Comment by JonathanMagnan** [comment]
Hello @stamminator ,

The v3.0.1 has been released.

`Precision` and `Scale` attribute are now supported.

Example:

```csharp
[StoredProcedureParameter(SqlDbType.Decimal, Precision = 5, Scale = 2)]
public Decimal? ParameterDecimal { get; set; }
```
