### ISSUE TITLE
SQL errors silently fail

### ISSUE THREAD

**Issue by daveb84** [zzzprojects/EntityFrameworkExtras#36]
Hi there,

I'm using the `ExecuteStoredProcedure` extension method to run a stored proc.  It's all working fine, but when the underlying stored procedure failed due to a key constraint violation, no exception was thrown, so it failed silently.

Is there anyway to ensure that any exceptions that occur at database level are bubbled and thrown?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @daveb84 ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

From what I know, we don't make any silence try/catch.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
