### ISSUE TITLE
EntityFrameworkExtras.EFCore5 nuget package is empty

### ISSUE THREAD

**Issue by bfalala** [zzzprojects/EntityFrameworkExtras#45]
https://github.com/zzzprojects/EntityFrameworkExtras/blob/f0f4a41482f676910aa2650bd2ab7d4ebefea2c2/EntityFrameworkExtras.EFCore5/EntityFrameworkExtras.EFCore5.csproj#L29

Hello,
I wanted to use this library on EFCore 5 but it's impossible to reference in my code. I guess it's because this line is missing in csproj:
`<Import Project="..\EntityFrameworkExtras.Shared\EntityFrameworkExtras.Shared.projitems" Label="Shared" />`

Can you please fix it ?

**Comment by JonathanMagnan** [comment]
Hello @bfalala ,

Thank you for reporting, you are indeed right!

It should be done later tomorrow or tonight (it seems GitHub is currently bugged, we cannot push code since the last 3h).

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @bfalala ,

A new version has been released today and the missing code committed: https://github.com/zzzprojects/EntityFrameworkExtras/blob/master/EntityFrameworkExtras.EFCore5/EntityFrameworkExtras.EFCore5.csproj#L30

Let me know if everything is now working as expected.

Best Regards,

Jon

**Comment by bfalala** [comment]
Hello @JonathanMagnan,

It's working fine now 👍 

Thanks !
